# Generated by Django 4.2.3 on 2023-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(auto_created=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
