# Generated by Django 4.2.3 on 2023-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
